### ISSUE TITLE
projects listing in table

### ISSUE THREAD

**Issue by Tarak1246** [TeamCodeCrafterss/CodeCrafters#75]
when there are no projects, it should show an empty table or proper message. Currently, it's looking like this.
![image](https://github.com/TeamCodeCrafterss/CodeCrafters/assets/36734811/6f8728b5-a914-4c71-9c70-00d19e84c22d)

**Comment by satyaaneesh98** [comment]
The page now shows that there are no projects to display if there are no projects added or available in the database.

**Comment by satyaaneesh98** [comment]
![image](https://github.com/TeamCodeCrafterss/CodeCrafters/assets/156818673/f3221461-7d8c-4fa6-9045-6e45fbdde0a0)
